### ISSUE TITLE
Таймкоды выступлений

### ISSUE THREAD

**Issue by mbelsky** [Semigradsky/events#2]
Добрый день,

Не совсем понял механику добавления новых событий в README.md, не в ручную ведь редактируется?
Есть ли опция добавления таймкодов в ссылки с записями выступлений?

**Comment by Semigradsky** [comment]
> Не совсем понял механику добавления новых событий в README.md, не в ручную ведь редактируется?

Добавляется/редактируется `yaml` файл в папке `events`. При пуше изменений будет атоматически сгенерированы `md` файлы.

> Есть ли опция добавления таймкодов в ссылки с записями выступлений?

Если это ссылка на видео на Youtube, то там можно добавлять в ссылку в виде `&t=2766s`. Как здесь:  https://github.com/Semigradsky/events/blob/master/events/RND.JS/2018-09-08%20RND.JS%207.yaml
